included:
  - KinoPub
variable_name:
  min_length: # not possible to disable this partial rule, so set it to zero
    warning: 0
    error: 0

disabled_rules:
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - todo
  - type_body_length
  - line_length
  # - vertical_whitespace
  - syntactic_sugar
  - nesting
  - trailing_whitespace

enabled_rules:
  - explicit_top_level_acl
  - explicit_acl

  - class_delegate_protocol
  - closing_brace
  - colon
  - comma
  - compiler_protocol_init
  - control_statement
  - discouraged_direct_init
  - dynamic_inline
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - generic_type_name
  - implicit_getter
  - inert_defer
  - is_disjoint
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - mark
  - no_fallthrough_only
  - notification_center_detachment
  - opening_brace
  - operator_whitespace
  - private_over_fileprivate
  - protocol_property_accessors_order
  - redundant_set_access_control
  - redundant_void_return
  - redundant_string_enum_value
  - return_arrow_whitespace
  - shorthand_operator
  - statement_position
  - switch_case_alignment
  - syntactic_sugar
  - trailing_comma
  - trailing_semicolon
  - unneeded_break_in_switch
  - unused_enumerated
  - weak_delegate
  - xctfail_message
  - custom_rules

  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - identical_operands
  - sorted_first_last
  - switch_case_on_newline
  - toggle_bool
  - untyped_error_in_catch
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - yoda_condition

  - literal_expression_end_indentation
  - empty_count
  - force_unwrapping

  - cyclomatic_complexity

  - force_try

  - redundant_discardable_let
  - redundant_optional_initialization

  - trailing_newline

  - unused_closure_parameter
  - unused_optional_binding
  - valid_ibinspectable
  - vertical_whitespace
  - void_return
